<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
<script>

function MyPromise(callback){
  let self=this;
  self.status="pending";
  self.resolveValue=undefined;
  self.rejectValue=undefined;
  self.successFnArray=[];
  self.errFnArray=[];
  function resolve(resolveValue){
      if(self.status=="pending"){
          self.status="resolve";
          self.resolveValue=resolveValue;
          self.successFnArray.forEach(function(item){
           item()
          })
      }
      
  }
  function reject(rejectValue){
    if(self.status=="pending"){
          self.status="reject";
          self.rejectValue=rejectValue;
          self.errFnArray.forEach(function(item){
           item()
          })
    }
   
  }
  //如果在执行callback函数的时候,如果抛出错误异常,应该走reject
  try {
     callback(resolve,reject)
  } catch (error) {
     reject(error)
  }
 


}
MyPromise.prototype.then=function(success,err){
  let self=this;
  if(self.status=="resolve"){
    success(self.resolveValue)
  }else if(self.status=="reject"){
    err(self.rejectValue)
  }else if(self.status=="pending"){
    self.successFnArray.push(function(){
      success(self.resolveValue)
    });
    self.errFnArray.push(function(){
      err(self.rejectValue)
    });
  }
}
let f1=new MyPromise(function(resolve,reject){
    throw new Error("出错")
    window.setTimeout(function(){ 
      resolve(100)                
                                  
    },1000)
    
});
f1.then(function(data){
    console.log(data)
},function(err){
    console.log("err3"+err)
});


</script>